2023/01/06 19:46:29 [emerg] 25540#24656: bind() to 0.0.0.0:80 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions)
2023/01/06 19:51:09 [error] 22848#11728: *1 CreateFile() "E:\Poly\SEM6\IT3552 Cyber Security Project\TargetWebsite\nginx-1.22.1\nginx-1.22.1/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/"
2023/01/06 20:09:52 [error] 1324#10088: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://[::1]:5000/", host: "localhost:81"
2023/01/06 20:10:26 [error] 1324#10088: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://[::1]:5000/", host: "localhost:81"
2023/01/06 20:13:13 [error] 1324#10088: *12 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://[::1]:5000/", host: "localhost:81"
2023/01/06 20:16:40 [error] 1324#10088: *20 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://[::1]:5000/", host: "localhost:81"
2023/01/06 20:33:28 [error] 13828#27372: *5 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/ HTTP/1.1", upstream: "http://[::1]:50010/myapp/", host: "127.0.0.1:5000"
2023/01/06 20:38:44 [error] 13828#27372: *12 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /unavailable HTTP/1.1", upstream: "http://[::1]:50010/unavailable", host: "127.0.0.1:5000"
2023/01/06 20:48:32 [error] 13828#27372: *19 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/ HTTP/1.1", upstream: "http://[::1]:50010/myapp/", host: "127.0.0.1:5000"
2023/01/06 20:53:47 [error] 13828#27372: *26 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /unavailable HTTP/1.1", upstream: "http://[::1]:50010/unavailable", host: "127.0.0.1:5000"
2023/01/06 21:02:23 [error] 1324#10088: *39 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://[::1]:5000/", host: "127.0.0.1:81"
2023/01/06 21:03:59 [error] 1324#10088: *46 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://[::1]:5000/", host: "127.0.0.1:81"
2023/01/06 21:07:21 [error] 1324#10088: *51 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://[::1]:5000/", host: "127.0.0.1:81"
2023/01/06 21:09:27 [error] 1324#10088: *59 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://[::1]:5000/", host: "127.0.0.1:81"
2023/01/06 21:14:43 [error] 1324#10088: *68 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://[::1]:5000/", host: "127.0.0.1:81"
2023/01/06 21:15:18 [error] 1324#10088: *73 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://[::1]:5000/", host: "localhost:81"
2023/01/06 21:15:49 [emerg] 8212#2276: "server" directive is not allowed here in E:\Poly\SEM6\IT3552 Cyber Security Project\TargetWebsite\nginx-1.22.1\nginx-1.22.1/conf/nginx.conf:80
2023/01/06 21:19:22 [emerg] 13628#1040: "server" directive is not allowed here in E:\Poly\SEM6\IT3552 Cyber Security Project\TargetWebsite\nginx-1.22.1\nginx-1.22.1/conf/nginx.conf:80
2023/01/06 21:19:29 [error] 1324#10088: *83 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://[::1]:5000/", host: "127.0.0.1:81"
2023/01/06 21:28:31 [emerg] 4148#15796: "server" directive is not allowed here in E:\Poly\SEM6\IT3552 Cyber Security Project\TargetWebsite\nginx-1.22.1\nginx-1.22.1/conf/nginx.conf:80
2023/01/06 21:30:20 [emerg] 27876#14444: unexpected "}" in E:\Poly\SEM6\IT3552 Cyber Security Project\TargetWebsite\nginx-1.22.1\nginx-1.22.1/conf/nginx.conf:89
2023/01/06 22:20:40 [emerg] 12884#11328: unexpected "}" in E:\Poly\SEM6\IT3552 Cyber Security Project\TargetWebsite\nginx-1.22.1\nginx-1.22.1/conf/nginx.conf:90
2023/01/06 22:21:38 [emerg] 23632#3532: unexpected "}" in E:\Poly\SEM6\IT3552 Cyber Security Project\TargetWebsite\nginx-1.22.1\nginx-1.22.1/conf/nginx.conf:90
2023/01/06 22:34:01 [notice] 24788#18768: signal process started
2023/01/06 22:37:35 [notice] 22884#23980: signal process started
2023/01/06 22:39:10 [emerg] 11968#12992: invalid host in "http://localhost:5000/myapp/" of the "listen" directive in E:\Poly\SEM6\IT3552 Cyber Security Project\TargetWebsite\nginx-1.22.1\nginx-1.22.1/conf/nginx.conf:85
2023/01/06 22:39:20 [emerg] 9036#1076: invalid host in "http://localhost:5000/myapp/" of the "listen" directive in E:\Poly\SEM6\IT3552 Cyber Security Project\TargetWebsite\nginx-1.22.1\nginx-1.22.1/conf/nginx.conf:85
2023/01/06 22:39:25 [emerg] 24876#24320: invalid host in "http://localhost:5000/myapp/" of the "listen" directive in E:\Poly\SEM6\IT3552 Cyber Security Project\TargetWebsite\nginx-1.22.1\nginx-1.22.1/conf/nginx.conf:85
2023/01/06 22:40:10 [emerg] 24580#1440: invalid host in "http://127.0.0.1:5000/myapp/" of the "listen" directive in E:\Poly\SEM6\IT3552 Cyber Security Project\TargetWebsite\nginx-1.22.1\nginx-1.22.1/conf/nginx.conf:85
2023/01/06 22:48:11 [emerg] 23764#28356: invalid host in "http://127.0.0.1:5000/myapp/" of the "listen" directive in E:\Poly\SEM6\IT3552 Cyber Security Project\TargetWebsite\nginx-1.22.1\nginx-1.22.1/conf/nginx.conf:85
2023/01/06 22:48:16 [emerg] 5544#12112: invalid host in "http://127.0.0.1:5000/myapp/" of the "listen" directive in E:\Poly\SEM6\IT3552 Cyber Security Project\TargetWebsite\nginx-1.22.1\nginx-1.22.1/conf/nginx.conf:85
2023/01/06 22:50:29 [error] 22848#11728: *7 CreateFile() "E:\Poly\SEM6\IT3552 Cyber Security Project\TargetWebsite\nginx-1.22.1\nginx-1.22.1/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8080", referrer: "http://127.0.0.1:8080/"
2023/01/06 22:54:00 [emerg] 18600#1468: "server" directive is not allowed here in E:\Poly\SEM6\IT3552 Cyber Security Project\TargetWebsite\nginx-1.22.1\nginx-1.22.1/conf/nginx.conf:80
2023/01/06 23:56:34 [error] 1324#10088: *87 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://[::1]:5000/", host: "127.0.0.1:81"
2023/01/06 23:59:20 [error] 16672#11352: *1 CreateFile() "E:\Poly\SEM6\IT3552 Cyber Security Project\TargetWebsite\nginx-1.22.1\nginx-1.22.1/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:1234", referrer: "http://127.0.0.1:1234/"
2023/01/07 00:25:44 [notice] 28300#16336: signal process started
2023/01/07 00:46:17 [error] 28360#25000: *1 CreateFile() "E:\Poly\SEM6\IT3552 Cyber Security Project\TargetWebsite\nginx-1.22.1\nginx-1.22.1/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8080", referrer: "http://127.0.0.1:8080/"
2023/01/07 00:47:46 [error] 4052#22968: *1 CreateFile() "E:\Poly\SEM6\IT3552 Cyber Security Project\TargetWebsite\nginx-1.22.1\nginx-1.22.1/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:1234", referrer: "http://127.0.0.1:1234/"
2023/01/07 00:47:49 [error] 28360#25000: *3 CreateFile() "E:\Poly\SEM6\IT3552 Cyber Security Project\TargetWebsite\nginx-1.22.1\nginx-1.22.1/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8080", referrer: "http://127.0.0.1:8080/"
2023/01/07 00:48:28 [error] 28360#25000: *5 CreateFile() "E:\Poly\SEM6\IT3552 Cyber Security Project\TargetWebsite\nginx-1.22.1\nginx-1.22.1/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8080", referrer: "http://127.0.0.1:8080/"
2023/01/07 00:48:31 [alert] 28360#25000: 1024 worker_connections are not enough
2023/01/07 00:48:31 [error] 28360#25000: *1027 WSARecv() failed (10053: An established connection was aborted by the software in your host machine) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/
2023/01/07 00:48:46 [alert] 28360#25000: 1024 worker_connections are not enough
2023/01/07 00:48:46 [error] 28360#25000: *2049 WSARecv() failed (10053: An established connection was aborted by the software in your host machine) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/
2023/01/07 00:50:10 [error] 28360#25000: *2053 CreateFile() "E:\Poly\SEM6\IT3552 Cyber Security Project\TargetWebsite\nginx-1.22.1\nginx-1.22.1/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8080", referrer: "http://127.0.0.1:8080/"
2023/01/07 00:51:56 [error] 4052#22968: *3 CreateFile() "E:\Poly\SEM6\IT3552 Cyber Security Project\TargetWebsite\nginx-1.22.1\nginx-1.22.1/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:1234", referrer: "http://127.0.0.1:1234/"
2023/01/07 00:55:34 [error] 27344#25396: *1 access forbidden by rule, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8080", referrer: "http://127.0.0.1:8080/"
2023/01/07 00:58:31 [error] 27344#25396: *7 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/ HTTP/1.1", upstream: "http://[::1]:5000/myapp/myapp/", host: "127.0.0.1:5000"
2023/01/07 00:58:31 [alert] 27344#25396: 1024 worker_connections are not enough
2023/01/07 00:58:31 [error] 27344#25396: *1028 WSARecv() failed (10053: An established connection was aborted by the software in your host machine) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/
2023/01/07 00:58:31 [error] 27344#25396: *1028 no live upstreams while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/my
2023/01/07 00:58:47 [error] 27344#25396: *1032 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/unavailable HTTP/1.0", upstream: "http://[::1]:5000/myapp/myapp/unavailable", host: "localhost:5000"
2023/01/07 00:58:47 [error] 27344#25396: *1032 no live upstreams while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/unavailable HTTP/1.0", upstream: "http://localhost/myapp/myapp/unavailable", host: "localhost:5000"
2023/01/07 01:03:33 [error] 27344#25396: *1038 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/myapp/ HTTP/1.0", upstream: "http://[::1]:5000/myapp/myapp/myapp/myapp/", host: "localhost:5000"
2023/01/07 01:03:34 [alert] 27344#25396: 1024 worker_connections are not enough
2023/01/07 01:03:34 [error] 27344#25396: *2055 WSARecv() failed (10053: An established connection was aborted by the software in your host machine) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/
2023/01/07 01:03:34 [error] 27344#25396: *2055 no live upstreams while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/my
2023/01/07 01:03:47 [error] 27344#25396: *2059 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/unavailable HTTP/1.0", upstream: "http://[::1]:5000/myapp/myapp/unavailable", host: "localhost:5000"
2023/01/07 01:03:47 [error] 27344#25396: *2059 no live upstreams while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/unavailable HTTP/1.0", upstream: "http://localhost/myapp/myapp/unavailable", host: "localhost:5000"
2023/01/07 01:08:28 [error] 27344#25396: *2065 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/myapp/ HTTP/1.0", upstream: "http://[::1]:5000/myapp/myapp/myapp/myapp/", host: "localhost:5000"
2023/01/07 01:08:29 [alert] 27344#25396: 1024 worker_connections are not enough
2023/01/07 01:08:29 [error] 27344#25396: *3082 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/my
2023/01/07 01:08:29 [error] 27344#25396: *3082 no live upstreams while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/my
2023/01/07 01:08:49 [error] 27344#25396: *3086 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/unavailable HTTP/1.0", upstream: "http://[::1]:5000/myapp/myapp/unavailable", host: "localhost:5000"
2023/01/07 01:08:49 [error] 27344#25396: *3086 no live upstreams while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/unavailable HTTP/1.0", upstream: "http://localhost/myapp/myapp/unavailable", host: "localhost:5000"
2023/01/07 01:13:29 [error] 27344#25396: *3092 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/myapp/ HTTP/1.0", upstream: "http://[::1]:5000/myapp/myapp/myapp/myapp/", host: "localhost:5000"
2023/01/07 01:13:29 [alert] 27344#25396: 1024 worker_connections are not enough
2023/01/07 01:13:29 [error] 27344#25396: *4109 WSARecv() failed (10053: An established connection was aborted by the software in your host machine) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/
2023/01/07 01:13:29 [error] 27344#25396: *4109 no live upstreams while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/my
2023/01/07 01:13:45 [error] 27344#25396: *4113 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/unavailable HTTP/1.0", upstream: "http://[::1]:5000/myapp/myapp/unavailable", host: "localhost:5000"
2023/01/07 01:13:45 [error] 27344#25396: *4113 no live upstreams while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/unavailable HTTP/1.0", upstream: "http://localhost/myapp/myapp/unavailable", host: "localhost:5000"
2023/01/07 01:23:32 [error] 27344#25396: *4119 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/myapp/ HTTP/1.0", upstream: "http://[::1]:5000/myapp/myapp/myapp/myapp/", host: "localhost:5000"
2023/01/07 01:23:33 [alert] 27344#25396: 1024 worker_connections are not enough
2023/01/07 01:23:33 [error] 27344#25396: *5136 WSARecv() failed (10053: An established connection was aborted by the software in your host machine) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/
2023/01/07 01:23:33 [error] 27344#25396: *5136 no live upstreams while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/my
2023/01/07 01:23:47 [error] 27344#25396: *5140 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/unavailable HTTP/1.0", upstream: "http://[::1]:5000/myapp/myapp/unavailable", host: "localhost:5000"
2023/01/07 01:23:47 [error] 27344#25396: *5140 no live upstreams while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/unavailable HTTP/1.0", upstream: "http://localhost/myapp/myapp/unavailable", host: "localhost:5000"
2023/01/07 01:24:36 [error] 27344#25396: *5147 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/myapp/ HTTP/1.0", upstream: "http://[::1]:5000/myapp/myapp/myapp/myapp/", host: "localhost:5000"
2023/01/07 01:24:37 [alert] 27344#25396: 1024 worker_connections are not enough
2023/01/07 01:24:37 [error] 27344#25396: *6164 WSARecv() failed (10053: An established connection was aborted by the software in your host machine) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/
2023/01/07 01:24:37 [error] 27344#25396: *6164 no live upstreams while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/my
2023/01/07 01:28:31 [error] 27344#25396: *6168 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/ HTTP/1.0", upstream: "http://[::1]:5000/myapp/myapp/myapp/", host: "localhost:5000"
2023/01/07 01:28:31 [error] 27344#25396: *6168 no live upstreams while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/ HTTP/1.0", upstream: "http://localhost/myapp/myapp/myapp/", host: "localhost:5000"
2023/01/07 01:28:46 [error] 27344#25396: *6174 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/unavailable HTTP/1.0", upstream: "http://[::1]:5000/myapp/myapp/myapp/unavailable", host: "localhost:5000"
2023/01/07 01:28:47 [alert] 27344#25396: 1024 worker_connections are not enough
2023/01/07 01:28:47 [error] 27344#25396: *7191 WSARecv() failed (10053: An established connection was aborted by the software in your host machine) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/
2023/01/07 01:28:47 [error] 27344#25396: *7191 no live upstreams while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/my
2023/01/07 01:31:40 [emerg] 13616#11616: unexpected "}" in E:\Poly\SEM6\IT3552 Cyber Security Project\TargetWebsite\nginx-1.22.1\nginx-1.22.1/conf/nginx.conf:121
2023/01/07 01:32:24 [emerg] 12140#21148: invalid number of arguments in "include" directive in E:\Poly\SEM6\IT3552 Cyber Security Project\TargetWebsite\nginx-1.22.1\nginx-1.22.1/conf/nginx.conf:119
2023/01/07 01:32:42 [notice] 11648#11184: signal process started
2023/01/07 01:32:42 [error] 11648#11184: OpenEvent("Global\ngx_reload_7828") failed (5: Access is denied)
2023/01/07 01:33:08 [emerg] 25028#5280: bind() to 0.0.0.0:80 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions)
2023/01/07 01:33:27 [error] 27344#25396: *7195 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/ HTTP/1.0", upstream: "http://[::1]:5000/myapp/myapp/myapp/", host: "localhost:5000"
2023/01/07 01:33:27 [error] 27344#25396: *7195 no live upstreams while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/ HTTP/1.0", upstream: "http://localhost/myapp/myapp/myapp/", host: "localhost:5000"
2023/01/07 01:33:49 [error] 27344#25396: *7201 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/unavailable HTTP/1.0", upstream: "http://[::1]:5000/myapp/myapp/myapp/unavailable", host: "localhost:5000"
2023/01/07 01:33:49 [alert] 27344#25396: 1024 worker_connections are not enough
2023/01/07 01:33:49 [error] 27344#25396: *8218 WSARecv() failed (10053: An established connection was aborted by the software in your host machine) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/
2023/01/07 01:33:49 [error] 27344#25396: *8218 no live upstreams while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/myapp/my
2023/01/07 01:34:00 [error] 27344#25396: *8220 access forbidden by rule, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8080", referrer: "http://127.0.0.1:8080/"
2023/01/07 01:44:05 [emerg] 2052#16912: bind() to 0.0.0.0:80 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions)
2023/01/07 01:44:29 [emerg] 2016#23696: bind() to 0.0.0.0:80 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions)
2023/01/07 01:46:21 [notice] 11640#20568: signal process started
2023/01/07 01:46:21 [error] 11640#20568: OpenEvent("Global\ngx_reload_7828") failed (2: The system cannot find the file specified)
2023/01/07 01:51:52 [emerg] 15544#18420: bind() to 0.0.0.0:80 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions)
2023/01/07 01:52:18 [emerg] 3788#12812: bind() to 0.0.0.0:80 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions)
2023/01/07 02:08:03 [emerg] 24104#22464: bind() to 0.0.0.0:80 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions)
2023/01/07 02:08:06 [emerg] 23104#24100: bind() to 0.0.0.0:80 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions)
2023/01/07 02:16:02 [emerg] 20124#7444: bind() to 0.0.0.0:80 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions)
2023/01/07 02:16:49 [emerg] 25888#23092: bind() to 0.0.0.0:80 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions)
